### ISSUE TITLE
Testing Running tests

### ISSUE THREAD

**Issue by snaketron** [HAMdetector/Escape.jl#1]
Hi Daniel,

I was testing Escape.jl and run into the error message shown below. 

Any idea what might have gone wrong (probably my mistake)?

Btw: naturally the same issue arises when I run the example:

```
using Escape

data = HLAData(
    alignment_file = "/home/user/Desktop/alignment.fasta",
    tree_file = "/home/user/Desktop/phylogeny.tree"
)
```
Best,
Simo

---------------------------------------------------------------------
(@v1.6) pkg> test Escape
     Testing Escape
      Status `/tmp/jl_dAaeH8/Project.toml`
 
....

     Testing Running tests...
Test Summary:               | Pass  Total
HLAAllele(::AbstractString) |    3      3
Test Summary:                   | Pass  Total
HLAType(::NTuple{6, HLAAllele}) |    2      2
Test Summary:                 | Pass  Total
hla_matrix(::Vector{HLAType}) |    1      1
Test Summary:                              | Pass  Total
hla_matrix_standardized(::Vector{HLAType}) |    1      1
Test Summary:                   | Pass  Total
Base.in(::HLAAllele, ::HLAType) |    5      5
Test Summary:                        | Pass  Total
Base.:(==)(::HLAAllele, ::HLAAllele) |    2      2
Test Summary:                | Pass  Total
is_valid_allele(::HLAAllele) |    4      4
Test Summary:                         | Pass  Total
Base.isless(::HLAAllele, ::HLAAllele) |    7      7
Test Summary:                  | Pass  Total
parse_allele(::AbstractString) |   12     12
Test Summary:      | Pass  Total
parse_allele(x...) |    2      2
Test Summary:       | Pass  Total
string(::HLAAllele) |    2      2
Test Summary:                   | Pass  Total
limit_hla_accuracy(::HLAAllele) |    3      3
Test Summary:               | Pass  Total
rand(::HLAAllele, ::Symbol) |    7      7
Test Summary:   | Pass  Total
rand(::HLAType) |    3      3
Test Summary:  | Pass  Total
unique_alleles |    2      2
Test Summary:             | Pass  Total
hla_accuracy(::HLAAllele) |    5      5
HLAData(::String, ::String, ::Vector{HLAType}): Error During Test at /home/sktron/.julia/packages/Escape/LH1pQ/test/hla_data.jl:1
  Got exception outside of a @test
  MethodError: no method matching add_vertex!(::MetaDiGraph{Int64, Float64})
  Closest candidates are:
    add_vertex!(::SimpleDiGraph{T}) where T at /home/sktron/.julia/packages/LightGraphs/IgJif/src/SimpleGraphs/simpledigraph.jl:449
    add_vertex!(::SimpleGraph{T}) where T at /home/sktron/.julia/packages/LightGraphs/IgJif/src/SimpleGraphs/simplegraph.jl:526
  Stacktrace:
    [1] phylogenetic_tree(newick_string::String)
      @ Escape ~/.julia/packages/Escape/LH1pQ/src/phylogenetic_tree.jl:12
    [2] macro expansion
      @ ~/.julia/packages/Escape/LH1pQ/test/hla_data.jl:10 [inlined]
    [3] macro expansion
      @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
    [4] top-level scope
      @ ~/.julia/packages/Escape/LH1pQ/test/hla_data.jl:2
    [5] include(fname::String)
      @ Base.MainInclude ./client.jl:444
    [6] top-level scope
      @ ~/.julia/packages/Escape/LH1pQ/test/runtests.jl:21
    [7] include(fname::String)
      @ Base.MainInclude ./client.jl:444
    [8] top-level scope
      @ none:6
    [9] eval
      @ ./boot.jl:360 [inlined]
   [10] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:261
   [11] _start()
      @ Base ./client.jl:485
Test Summary:                                  | Pass  Error  Total
HLAData(::String, ::String, ::Vector{HLAType}) |    2      1      3
ERROR: LoadError: LoadError: Some tests did not pass: 2 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /home/sktron/.julia/packages/Escape/LH1pQ/test/hla_data.jl:1
in expression starting at /home/sktron/.julia/packages/Escape/LH1pQ/test/runtests.jl:21
ERROR: Package Escape errored during testing

**Comment by HAMdetector** [comment]
Hi Simo,

thank you for opening this issue! This problem was caused by the discontinuation of the LightGraphs.jl package, which is now called Graphs.jl. I replaced the dependency and also added proper upper version bounds to the [compat] section of the Project.toml, which should avoid similar problems in the future.

Please don't hesitate to open further issues if you encounter any errors.

**Comment by snaketron** [comment]
wow, thank you for solving the issue so fast! 

The package runs smoothly now.
