### ISSUE TITLE
Minor points on Escape.replacement_summary & Escape.run_model

### ISSUE THREAD

**Issue by snaketron** [HAMdetector/Escape.jl#2]
Hi Daniel,

first of all Escape.jl (v0.1.4) is an excellent piece of software!

Please find listed some technical points/experiences that might be relevant to you/future users:

1) `summary = replacement_summary(result)`
columns fisher_p, n_replacement_total and n_replacement_with_hla are set to 0 when I run the above function

2) `result = Escape.run_model(data, chains = 4, iter = 1000, warmup = 300, stan_args = "adapt_delta=0.95")`
"adapt_delta" -> "adapt delta" (no underscore appears to work) 

Best,
Simo

**Comment by HAMdetector** [comment]
Hi Simo, sorry for not replying to this issue at all, I totally forgot. But better late than never I hope.

1. the columns are only populated if the `fisher_p` keyword is set to true. For now, I replaced the default value of 0 with `missing` so it is hopefully less confusing.

2. Just updated the documentation. Thank you for spotting this!
